#!/bin/sh

hostname="$(hostname)"
	
if [ "$hostname" = notebook ]
then
	batsignal -b -e -w 20 -c 10 -d 5
	
	bspc monitor -d 1 2 3 4 5
elif [ "$hostname" = desktop ]
then
	bspc monitor HDMI-A-1 -d 1 2 3
	bspc monitor HDMI-A-0 -d 4 5 6

	polychromatic-cli -d keyboard -o static -c '#8000FF'
	polychromatic-cli -d mouse -z scroll -o static -c '#8000FF'
	polychromatic-cli -d mouse -z logo -o static -c '#8000FF'
fi

gnome-keyring-daemon --start

polybar "$hostname" &
sxhkd &
dunst &
picom -b
blueman-applet &
rclone mount "Google Drive:" "$HOME/Google Drive" &
thunar --daemon &
a2ln &

xwallpaper --stretch "$HOME/Pictures/.background"

xsetroot -cursor_name left_ptr

wmname LG3D

bspc config window_gap 13
bspc config border_width 0

floating-window everytime 'iwgtk'
floating-window everytime 'Blueman-manager'
floating-window everytime 'Pavucontrol'
floating-window everytime 'Bitwarden'
floating-window everytime 'Galculator'
