#!/bin/sh

if [ "$HOSTNAME" = notebook ]
then
    $HOME/.scripts/battery notify &

    bspc monitor -d 1 2 3 4 5 6 7 8
elif [ "$HOSTNAME" = desktop ]
then
    bspc monitor HDMI-A-1 -d 1 2 3 4
    bspc monitor HDMI-A-0 -d 5 6 7 8

    polychromatic-cli -d keyboard -o static -c '#8000FF'
    polychromatic-cli -d mouse -z scroll -o static -c '#8000FF'
    polychromatic-cli -d mouse -z logo -o static -c '#8000FF'
fi

eww daemon
eww open bar
sxhkd &
dunst &
picom -b
blueman-applet &
rclone mount "drive:" "$HOME/Google Drive" &
thunar --daemon &
a2ln &

$HOME/.scripts/player &
$HOME/.scripts/desktops &

gnome-keyring-daemon -s

xwallpaper --stretch "$HOME/Pictures/.background.png"

xsetroot -cursor_name left_ptr

wmname LG3D

bspc config window_gap 8
bspc config border_width 0

bspc rule -a 'iwgtk' state=floating center=true
bspc rule -a 'Blueman-manager' state=floating center=true
bspc rule -a 'Pavucontrol' state=floating center=true
bspc rule -a 'Bitwarden' state=floating center=true
bspc rule -a 'Galculator' state=floating center=true
