#!/bin/sh

if ! [ -d "$SCREENSHOT_DIRECTORY" ]
then
	mkdir -p "$SCREENSHOT_DIRECTORY"
fi

local_file="$SCREENSHOT_DIRECTORY/$(date +'%Y-%m-%d-%H:%M:%S').png"

log_file="$SCREENSHOT_DIRECTORY/.log"

upload() {
	if response="$(curl -f -s -H "Authorization: Client-ID $IMGUR_API_KEY" -F "image=@$local_file" 'https://api.imgur.com/3/image.xml')"
	then
		url=$(echo "$response" | xml sel -t --value-of '/data/link')
		
		body='Uploaded to Imgur'

		echo "$url" | xclip -selection clipboard

		echo "$url $(printf 'https://imgur.com/delete/%s' $(echo "$response" | xml sel -t --value-of '/data/deletehash'))" >> "$log_file"
	else
		xclip -selection clipboard -t image/png -i "$local_file"
	fi

	notify-send -i "$HOME/Pictures/.zoom" 'Screenshot taken' "$body"
}

fullscreen() {
	shotgun -s "$local_file"

	upload
}

selection() {
	if ! selection=$(hacksaw -f "-i %i -g %g")
	then
		exit 1
	fi

	shotgun $selection "$local_file"

	upload
}

case "$1" in
	fullscreen)
		fullscreen
		;;
	selection)
		selection
		;;
	*)
		exit 1
		;;
esac
