#!/bin/sh

count() {
	(paru -Qum ; checkupdates) 2>/dev/null | wc -l
}

update() {
	if [ "$(count)" -eq 0 ] || [ -f /var/lib/pacman/db.lck ]
	then	
		exit 1
	fi
	
	floating-window once 'kitty paru'
}

case "$1" in
	count)
		count
		;;
	update)
		update
		;;
	*)
		exit 1
		;;
esac
